package com.android.triviaapp.models;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.android.triviaapp.models.GameDetails;

import com.android.triviaapp.models.GameDetailsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gameDetailsDaoConfig;

    private final GameDetailsDao gameDetailsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gameDetailsDaoConfig = daoConfigMap.get(GameDetailsDao.class).clone();
        gameDetailsDaoConfig.initIdentityScope(type);

        gameDetailsDao = new GameDetailsDao(gameDetailsDaoConfig, this);

        registerDao(GameDetails.class, gameDetailsDao);
    }
    
    public void clear() {
        gameDetailsDaoConfig.clearIdentityScope();
    }

    public GameDetailsDao getGameDetailsDao() {
        return gameDetailsDao;
    }

}
